name: create-workflows
on:
  push:
jobs:
    rw:
        runs-on: ubuntu-20.04
        steps:
            - name: checkout simulation data
              uses: actions/checkout@v4
              with: 
                submodules: true
                token: ${{ secrets.WRITE_WORKFLOW }}
            - name: install prerequisites
              run: |
                cd util/stmd
                npm install yaml
                cd ../..
                npm install --prefix ./Credibility-Assessment-Framework/Credibility-Development-Kit/util/stmd-crud ./Credibility-Assessment-Framework/Credibility-Development-Kit/util/stmd-crud
            - name: create new workflow
              env:          
                GithubBranch: ${{ github.ref_name }}
                GithubRepoName: ${{ github.event.repository.name }}
                GithubOwner: ${{ github.repository_owner }}
              run: node ./util/stmd/parse_to_yaml.js -f "./data/dc.motor/extra/net.pmsf.ssp.stmd/SimulationTask.stmd" -o ./.github/workflows
            - name: push workflows
              run: |
                git config --global user.name "Automated Test Pipeline"
                git config --global user.email "setlabs@users.noreply.github.com"

                git add ./.github/workflows
                git commit -m "Generated new automated all workflow, based on STMD [actions skip]"
                git push -f
                
            - name: display result
              run: |
                echo "Successfully created new workflows" >> $GITHUB_STEP_SUMMARY
                # cat ./.github/workflows/continuous_test.yml >> $GITHUB_STEP_SUMMARY
